### ISSUE TITLE
Error when using kubectl lock: KUBE-LOCK: Context evaluation failed: open : no such file or directory

### ISSUE THREAD

**Issue by swettoth0812** [ChaosInTheCRD/kube-lock#7]
Hi guys,

I am trying to use this tool, but after installing, I got an issue below in any command I run
```
KUBE-LOCK: Context evaluation failed: open : no such file or directory
```
I thought that it would be related to this issue, which is missing the profile: https://github.com/ChaosInTheCRD/kube-lock/issues/6
I created the ~/.kube-lock.yaml manually, but the error still appears.

```
contexts:
  - name: k0s-1
    status: protected
    unlockTimestamp: ""
profiles:
  - name: protected
    blockedVerbs:
      - delete
      - apply
      - create
      - patch
      - label
      - annotate
      - replace
      - cp
      - taint
      - drain
      - uncordon
      - cordon
      - auto-scale
      - scale
      - rollout
      - expose
      - run
      - set
    deleteExceptions:
      - group: cert-manager.io/v1
        resource: certificates
      - group: v1
        resource: pods
defaultProfile: protected
unlockTimeoutPeriod: ""
```
